version: "3.9"
services:
  flask-app:
    build: .
    ports:
      - "5000"
    depends_on:
      - db
    networks:
      - app-network 

  web:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3333:80"
    depends_on:
      - app
    networks:
      - app-network
  db:
    image: "mysql:latest"
    restart: always
    volumes:
      - fdb:/var/lib/fdb
    environment:
      - MYSQL_ROOT_PASSWORD:MY-PASS
    networks:
      - app-network  
volumes:
    fdb: {}
networks:
    app-network: {}